### ISSUE TITLE
Clip polygon edges to the extent.

### ISSUE THREAD

**Issue by mbostock** [observablehq/voronator#2]
If we want to apply [Liang–Barsky clipping](https://en.wikipedia.org/wiki/Liang–Barsky_algorithm), the Voronator will also need to know the clip extent.

**Comment by mourner** [comment]
You could also do Sutherland-Hodgeman for clipping ([like this](https://github.com/mapbox/lineclip/blob/master/index.js#L65)) — it's simpler, and it should be as fast as Liang-Barsky for this particular case since most of the cells are either inside or on the edge.

**Comment by mbostock** [comment]
Thanks for the pointer. d3-voronoi has Liang–Barsky, but it’s nice to have another algorithm implemented for comparison!

**Comment by w8r** [comment]
You could take a look at this [optimized version of Linang-Barsky](https://github.com/w8r/liang-barsky) that performs very good due to almost no additional memory allocations.

**Comment by mbostock** [comment]
Done!
